version: '3'
services:
  redis:
    image: 'redis:alpine'
    volumes:
      - .data:/redis/data
    ports:
      - 6379:6379
  dynamodb:
    image: 'amazon/dynamodb-local'
    volumes:
      - .data:/dynamodb/data
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /dynamodb/data/
  server:
    image: 'node:10-alpine'
    working_dir: /home/node/
    environment:
      REDIS_DB: redis
      REDIS_PASSWORD: ''
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DYNAMODB_REGION: 'us-east-1'
      AWS_ACCESS_KEY_ID: 'abc'
      AWS_SECRET_ACCESS_KEY: 'xyz'
    depends_on:
      - redis
    links:
      - redis:redis
    volumes:
      - ./:/home/node
    command: npm run dev
    ports:
      - 80:80
      - 443:443